version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
      
### Elasticsearch ################################################
    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:7.8.1
      environment:
        - discovery.type=single-node
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - backend 
        
### Kibana ################################################
    kibana:
      container_name: kibana
      image: kibana:7.8.1
      ports:
        - "5601:5601"
      networks:
        - backend 
        
### Cerebro ES集群可视化管理工具 ##########################
    cerebro:
      container_name: cerebro
      image: lmenezes/cerebro:0.9.2
      ports:
        - "9100:9000"
      command:
        - -Dhosts.0.host=http://elasticsearch:9200
      networks:
        - backend
        
### Logstash ##########################
    logstash:
      container_name: logstash
      image: logstash:7.8.1
      ports:
        - "5044:5044"
      volumes:
        - E:/work/laradock/elk-stack/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
        - E:/work/laradock/elk-stack/logstash/config/:/usr/share/logstash/conf.d/
        - E:/work/laradock/elk-stack/logstash/output-logs:/usr/share/logstash/output-logs
        - E:/work/laradock/elk-stack/logstash/logs:/usr/share/logstash/logs
      networks:
        - backend
        
### Filebeat ##########################
    filebeat:
      container_name: filebeat
      image: store/elastic/filebeat:7.8.1
      user: root
      ports:
        - "5044:5044"
      volumes:
        - E:/work/laradock/elk-stack/filebeat/logs:/usr/share/filebeat/logs
        - E:/work/laradock/elk-stack/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      networks:
        - backend
